### ISSUE TITLE
× TypeError: t.loadAll is not a function

### ISSUE THREAD

**Issue by throne1986** [Ju99ernaut/grapesjs-template-manager#10]
I get this error when I installed this plugin, I am using reactjs

![image](https://user-images.githubusercontent.com/27904724/128438366-15669fc8-1d41-4876-a34e-64c4b848b73f.png)

**Comment by Ju99ernaut** [comment]
Looks like an issue with your configuration, the suppored storage types are listed in the README.

**Comment by throne1986** [comment]
> Looks like an issue with your configuration, the supported storage types are listed in the README.

What do you mean by `storage types`?

**Comment by Ju99ernaut** [comment]
Check these sections :
https://github.com/Ju99ernaut/grapesjs-template-manager#localindexeddb
https://github.com/Ju99ernaut/grapesjs-template-manager#firestore
https://github.com/Ju99ernaut/grapesjs-template-manager#remoterest-api
