### ISSUE TITLE
Saving a template POSTs to an invalid URL

### ISSUE THREAD

**Issue by Biont** [Ju99ernaut/grapesjs-template-manager#14]
Fetching and updating regular documents works just fine, but when updating a page/template in the template manager modal, it adds an extra slash in the URL, resulting in a 404 on my back-end.

![screenshot_2021-09-06-130822](https://user-images.githubusercontent.com/4208996/132208574-3531b7ba-949c-4d48-943b-02a23dd9b773.png)

**Comment by Ju99ernaut** [comment]
I'll fix this in the next release.
