### ISSUE TITLE
Index Page Issues

### ISSUE THREAD

**Issue by Stage4000** [Ju99ernaut/grapesjs-template-manager#18]
The index page of a project doesnt have any functionality within the page list. For example: If you navigate away from index in the page list you cant navigate back to the index page in the page list, further, you are unable to rename or delete index at any point.

Is this another case of 'this guy is a moron'? or is this a legit bug?

Im not getting any console errors and my back end appears to be functioning correctly as far as I can tell.
Im still troubleshooting this issue but it appears that something isnt reading or setting the index ID. Index Page ID isnt being set on new project creation and causes the builder to not be able to interact with index.

**Comment by Dev-dpk** [comment]
I am having the same issue is this sorted out  ?

**Comment by Stage4000** [comment]
There were so many issues last time I tried this, I do believe we fixed this but this page and project manager isn't complete by a long shot.

**Comment by Ju99ernaut** [comment]
We didn't manage to fully resolve this, I personally couldn't find how this was an issue with the plugin itself as it seems to work well with the sample API, for remote storage all the plugin does is send `GET`, `POST` and `DELETE` requests and if everything is stored and returned correctly everything should work fine. Unfortunately I can't document how to implement the backend as it is beyond the scope of this plugin.
