### ISSUE TITLE
How to load multiple pages from api-rest storage

### ISSUE THREAD

**Issue by hela-Ch** [Ju99ernaut/grapesjs-template-manager#20]
Hi, can you please give me an exemple to load multiple pages from api-rest storage  and the structure of the data received from the api . On my console the pages array exists but on the editor and command show-pages i have nothing.
Tank you :)

**Comment by Ju99ernaut** [comment]
The data received from should be in this format https://github.com/Ju99ernaut/grapesjs-template-manager#remoterest-api. This is mostly generated by grapesjs.

**Comment by hela-Ch** [comment]
> The data received from should be in this format https://github.com/Ju99ernaut/grapesjs-template-manager#remoterest-api. This is mostly generated by grapesjs.

@Ju99ernaut  please  each page will have this format 
{
      "id": "UUIDv4",
      "name": "Page name",
      "template": false,
      "thumbnail": "",
      "description": "No description",
      "gjs-assets": "[]",
      "gjs-pages": "[]",
      "gjs-styles": "[]",
      "updated_at": ""
    }
 or all pages will be inside gjs-pages ??
Can you please give some exemple because i tried grapesjs structure with pages and styles and you project structure without success :/ I have been stuck for 3 days
For my project , when  a page is opened to edit it ,i want to load  also all pages from the same presentation and show them when i click the open-pages(take screenshot) button so i can switch between them
thank you :)

**Comment by Ju99ernaut** [comment]
This is the structure for each site, `gjs-pages` is a bit different and is generated from the editor.
```json
{
"id": "UUIDv4",
"name": "Page name",
"template": false,
"thumbnail": "",
"description": "No description",
"gjs-assets": "[]",
"gjs-pages": "[]",
"gjs-styles": "[]",
"updated_at": ""
}
```

**Comment by Ju99ernaut** [comment]
Each site can have multiple pages, stored in `gjs-pages` , you switch between sites using the `open-templates` command
![open-templates](https://user-images.githubusercontent.com/48953676/130074718-0e50d99a-d004-41e0-890c-66f05175e45c.png)
and between pages in a site using `open-pages`,  the `open-pages` command opens a panel on the right similar to the style manager.
![open-pages](https://user-images.githubusercontent.com/48953676/130074843-81c120f9-37a0-4ee1-b8d4-019a16de6a46.png)

**Comment by hela-Ch** [comment]
Thank you @Ju99ernaut :) 

1/ . Now i have a list of pages which belong to the same presentation when i click 'take screenshot" and i can switch between them !! but my page doesn't displays on the canvas! i have the json of the component instead :/
the images below show : 

- response for the initial load
- the load laravel api (get all slides which belong to the first presentation)
- what i get when a page get displayed

<img width="831" alt="Capture d’écran 2021-12-30 à 19 07 45" src="https://user-images.githubusercontent.com/78824411/147777676-1d8b81c7-f2e4-48d2-81b6-a29bfdb9ab1a.png">
<img width="1186" alt="Capture d’écran 2021-12-30 à 19 08 28" src="https://user-images.githubusercontent.com/78824411/147777679-ef1dc28a-7b4b-458d-90a5-a30c6e5db616.png">
<img width="1181" alt="Capture d’écran 2021-12-30 à 19 09 04" src="https://user-images.githubusercontent.com/78824411/147777681-617eecde-baf2-42d7-897d-a91a301fdb9e.png">
<img width="843" alt="Capture d’écran 2021-12-30 à 19 09 59" src="https://user-images.githubusercontent.com/78824411/147777682-ee552eb5-9e68-4236-aa21-bcba98fa5e8b.png">

2/. When i tried to load an array of presentations(each presentation has x number of pages) i have nothing on the list of sites and list of pages

**Comment by Ju99ernaut** [comment]
The issue might be with storage of `gjs-pages` it should be a string, so maybe json encode it too.

**Comment by hela-Ch** [comment]
@Ju99ernaut i tried to json encode gjs-pages too but it didn't solve the problem 
<img width="1440" alt="Capture d’écran 2021-12-31 à 10 08 34" src="https://user-images.githubusercontent.com/78824411/147814337-767022a0-7542-4510-b4dd-a26e1b48bb9c.png">

**Comment by Ju99ernaut** [comment]
I'm not really sure might be an issue with encoding the data, usually you receive the encoded string from the editor instead of encoding it backend, i.e. you receive the `gjs-pages`, `gjs-assets` and `gjs-styles` as strings from the editor, so you store them as strings and return them as is.

**Comment by hela-Ch** [comment]
Hello @Ju99ernaut , unfortunately i still cant find what is the problem :/ doesr the gjs-pages has the structure 
"gjs-pages": [{
     "styles": "....",
      "pages: [
          {
          id: ...,
          component: .....
          },
          {
          id: ...,
          component: .....
          }
  ]
]}
or this structure : 

"gjs-pages": [{
     "styles": "....",
      "pages: [
          {
          id: ...,
         frames: [{
                 component: { type: 'wrapper', ...}, // GrapesJS never stored data about the `wrapper`, now it does
                 html: '...',
                 css: '...', 
               }]
          },
          {
          id: ...,
          frames: [{
               component: { type: 'wrapper', ...}, // GrapesJS never stored data about the `wrapper`, now it does
               html: '...',
               css: '...', 
            }]
          }
   ]
]}
(because the data stored contains gjs-pages: frames
2/ Can i store each slide separately?
Thank you :)

**Comment by Ju99ernaut** [comment]
I'm not too sure of the structure of `gjs-pages`, a lot of it is generated by the editor and can vary depending on configuration. In general such an issue is caused when the editor fails to parse the contents of `component` so it just returns the string value.

I think you can store slides separately, you can handle data storage how you want on the backend as long as you'll be able to return the correct format.
