### ISSUE TITLE
Grapesjs adds "-2" to ids in the html with Firestore

### ISSUE THREAD

**Issue by koravski** [Ju99ernaut/grapesjs-template-manager#25]
Hi,
I'm using the template manager with firestore. But when I add some background to a page and open another project and come back again the id gets "-2" at the ends. Each time it gets a new "-2".

![Screenshot 2022-04-26 at 12 28 02](https://user-images.githubusercontent.com/7700986/165269041-2292e5e0-d678-414d-a0e0-12e8301c98f6.png)

Is there any solution?

Thanks.

**Comment by Ju99ernaut** [comment]
You can check this issue for reference https://github.com/artf/grapesjs/issues/4196
```js
editor.on('storage:start:load', () => {
     editor.Components.clear();
});
```
