### ISSUE TITLE
 add additional values ​​on page edit

### ISSUE THREAD

**Issue by vizardkill** [Ju99ernaut/grapesjs-template-manager#27]
Hi bro, it's me again.

I wanted to ask you if it is possible that in the editing part of the page you can add something like the title and description of the page?

![image](https://user-images.githubusercontent.com/37307788/167513546-ffa2b04d-5a1c-4d6d-bd3b-8ea698322fc8.png)

is that I want to do something like this, to add SEO on the pages

![image](https://user-images.githubusercontent.com/37307788/167513610-691e00f8-2741-436e-a21a-eb2b393ea709.png)

I know that grapes stores the structure of the pages in the gjs-pages property, so how do we embed new properties within the selected page?

**Comment by Ju99ernaut** [comment]
It is possible, basically something like:
```js
const sel = editor.Pages.getSelected();
// set value.
sel.set({ title: 'Title' });
// get value
sel.get('title');
```
