### ISSUE TITLE
Disable blocks depending on the page

### ISSUE THREAD

**Issue by vizardkill** [Ju99ernaut/grapesjs-template-manager#28]
My brother wanted to bother you again, and I have a question.

Is it possible to disable certain blocks when I select a page?

![image](https://user-images.githubusercontent.com/37307788/172500918-27a667b5-411b-49e8-b884-6f7751d3578b.png)

Suppose I want to disable certain blocks when the user selects the checkout page, because there are blocks that cannot be used unless they are on a specific page.

![image](https://user-images.githubusercontent.com/37307788/172501175-b780087b-b767-4463-8b7c-e2d0df395c07.png)

I was thinking of running a command where I get the BlockManager but I haven't found any functionality within the API that allows me to disable the blocks

**Comment by Ju99ernaut** [comment]
I don't think you can disable blocks, maybe you can filter out the blocks?

**Comment by vizardkill** [comment]
It can also be an option, I will give an example to understand what I want to achieve.

There are some blocks that are responsible for building the payment form at the time of completing a purchase for having added products to the cart.

In theory, the blocks that are part of the payment process should only exist when selecting the checkout page.

So we could:

a. Hide blocks visually

b. Disable blocks when changing a page using the BlockManager

c. Change the list of blocks every time a page is changed.

**Comment by Ju99ernaut** [comment]
I don't think you can disable the blocks from the API, the only option I can think of would be to filter out those blocks each time you switch to such a page so that they don't appear in the block manager.

**Comment by vizardkill** [comment]
If that seems to be the easiest option, I was looking at the api and indeed there is no method to do it.

I will take a look to make the filter and I will tell you if I could solve it through the filters
