### ISSUE TITLE
Display current page name

### ISSUE THREAD

**Issue by badiuciprian** [Ju99ernaut/grapesjs-template-manager#34]
Hi, I need to display the currently open page name somewhere to be visible without having to open the modal. Can it be achieved in some way? Thanks.
Also it would be very helpful to have a confirmation dialog when deleting a page.

**Comment by Ju99ernaut** [comment]
You can get the current page name by using `editor.Storage.getCurrentStorage().currentName)`.  Will look into adding a confirmation dialog or at least a way to configure one.
