### ISSUE TITLE
Could not initialize template manager

### ISSUE THREAD

**Issue by tboulogne** [Ju99ernaut/grapesjs-template-manager#6]
Hello,

When i try to initialize the manager got : 
![image](https://user-images.githubusercontent.com/6205275/115931421-59dd0b00-a48b-11eb-818e-5b1450abba62.png)

My storage manager conf:
![image](https://user-images.githubusercontent.com/6205275/115931482-75481600-a48b-11eb-8149-f348abe2c303.png)

Any idea to solve this please ?

Thanks for help. 

Regards

**Comment by Ju99ernaut** [comment]
Grapesjs' built in storages don't work with this plugin, here's the list of supported storage types and how to setup https://github.com/Ju99ernaut/grapesjs-template-manager#localindexeddb
