### ISSUE TITLE
How to save all created pages as a single project?

### ISSUE THREAD

**Issue by MuhammadMabrouk** [Ju99ernaut/grapesjs-template-manager#8]
Thanks for this great plugin
I want to save template pages at the end as a single project (multi-page website)
Can you tell me how to do that?

**Comment by Ju99ernaut** [comment]
The plugin doesn't have support for that yet. You can take a look at the [` page-manager`](https://github.com/artf/grapesjs/pull/3411) module to create something along those lines.
