### ISSUE TITLE
Plugin not found

### ISSUE THREAD

**Issue by diegoSenra** [Ju99ernaut/grapesjs-template-manager#9]
Hey! Can you giv me a hand? 
The 'plugin not found' message is appearing in my browser
it correctly loads the js and css files from unpkg but the editor cant find the plugin
Do you have any idea of what could be happening?

This is my editor:
var editor = grapesjs.init({
        height: '100%',
        //Store manager for templates
        storageManager: {
            //autoload: 0,
            type: 'rest-api',
            // the URIs below can be the same depending on your API design 
            urlStore: `${server}/Comunication/EmailContent/SaveTemplate`,// POST
            //urlLoad: 'https://endpoint/load/',// GET
            //urlDelete: 'https://endpoint/delete/',// DELETE
            params: { _some_token: '...' },
            headers: { Authorization: 'Basic ...' }
        },
        //Plugin and other configs
        container: '#gjs',
        fromElement: true,
        plugins: ['gjs-preset-newsletter', 'grapesjs-template-manager'],
        pluginsOpts: {
            'gjs-preset-newsletter': {
                codeViewerTheme: 'material',
                cellStyle: {
                    'font-size': '12px',
                    'font-weight': 300,
                    'vertical-align': 'top',
                    color: 'rgb(111, 119, 125)',
                    margin: 0,
                    padding: 0,
                }
            },
        }
    });

**Comment by diegoSenra** [comment]
Ah, my imports ate the top of the html page:
<link rel="stylesheet" href="./YDocEditor/style/grapes.css"> 
<link rel="stylesheet" href="./YDocEditor/style/material.css">
<link rel="stylesheet" href="./YDocEditor/style/tooltip.css">
<link rel="stylesheet" href="./YDocEditor/style/grapesjs-preset-newsletter.css">
<link rel="stylesheet" href="./YDocEditor/style/index.css">
<link rel="stylesheet" href="./YDocEditor/assetExplorer/style/style.css">
<link rel="stylesheet" href="https://unpkg.com/grapesjs-template-manager/dist/grapesjs-template-manager.min.css">
<script type="text/javascript" src="./YDocEditor/js/grapes.js"></script>
<script type="text/javascript" src="./YDocEditor/js/grapesjs-preset-newsletter.js"></script>
<script type="text/javascript" src="./YDocEditor/assetExplorer/js/index.js"></script>
<script src="https://unpkg.com/grapesjs-template-manager@1.0.7/dist/grapesjs-template-manager.min.js"></script>

GrapesJS files are local

**Comment by diegoSenra** [comment]
<link rel="stylesheet" href="./YDocEditor/style/grapes.css"> 
<link rel="stylesheet" href="./YDocEditor/style/material.css">
<link rel="stylesheet" href="./YDocEditor/style/tooltip.css">
<link rel="stylesheet" href="./YDocEditor/style/grapesjs-preset-newsletter.css">
<link rel="stylesheet" href="./YDocEditor/style/index.css">
<link rel="stylesheet" href="./YDocEditor/assetExplorer/style/style.css">
<link rel="stylesheet" href="https://unpkg.com/grapesjs-template-manager/dist/grapesjs-template-manager.min.css">
<script type="text/javascript" src="./YDocEditor/js/grapes.js"></script>
<script type="text/javascript" src="./YDocEditor/js/grapesjs-preset-newsletter.js"></script>
<script type="text/javascript" src="./YDocEditor/assetExplorer/js/index.js"></script>
<script src="https://unpkg.com/grapesjs-template-manager@1.0.7/dist/grapesjs-template-manager.min.js"></script>

grapesjs files are local

**Comment by i-polaris** [comment]
Hello, I having the same issue a you, i'm currently digging to see where the issue come from, i suspect a wrong config with grapesjs-cli

@diegoSenra  : did you made any progress on tihs issue ?

**Comment by diegoSenra** [comment]
Hi!
Well, did not make any progress. 
Actually I gave up and built my own custom template manager.

**Comment by Ju99ernaut** [comment]
Unfortunately I'm unable to reproduce this. Are you loading the js and css files in the head of the document?

**Comment by i-polaris** [comment]
i have to do  some test but @diegoSenra  and me are using gjs-preset-newsletter plugin, so it maybe create an incompatibility

**Comment by Ju99ernaut** [comment]
I haven't faced this issue even whilst using `gjs-preset-newsletter`.
